name: Docker Series Builds


on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build web
      run: |
        docker build . -t arunachalamrajesh/webapitest:latest
